# Generated by Django 4.2.2 on 2023-11-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='tasku',
        ),
    ]
