# Generated by Django 4.2.2 on 2023-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_task_tasku'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasku',
            name='date',
            field=models.DateField(default='1993-03-22'),
            preserve_default=False,
        ),
    ]
