# Generated by Django 4.2.2 on 2023-11-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_tasku_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasku',
            new_name='taski',
        ),
    ]
